universe = vanilla
executable = /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/restricted/submissions/20260816T230807Z_WT_A15xS8_F012_FCC_np1/scripts/run_full_control.sh
arguments = --mode $(mode) --seed-id $(seed_id) --campaign-dir /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/restricted/submissions/20260816T230807Z_WT_A15xS8_F012_FCC_np1 --output-root $(node_output_root)
initialdir = /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/restricted/submissions/20260816T230807Z_WT_A15xS8_F012_FCC_np1
should_transfer_files = NO
getenv = True
request_cpus = 1
request_memory = 3000MB
request_disk = 6000MB
+JobFlavour = "tomorrow"
output = logs/$(mode).$(ClusterId).$(ProcId).out
error = logs/$(mode).$(ClusterId).$(ProcId).err
log = logs/control.$(ClusterId).log
notification = Never
queue
