universe = vanilla

executable = run_d1d2_integration_v4.sh
arguments = D1_vamp2_np1 $(out_root)

output = logs/D1_vamp2_np1.$(ClusterId).$(ProcId).out
error  = logs/D1_vamp2_np1.$(ClusterId).$(ProcId).err
log    = logs/d1.$(ClusterId).log

request_cpus   = 1
request_memory = 3000MB
request_disk   = 6000MB

+JobFlavour = "tomorrow"

getenv = True
should_transfer_files = NO

queue out_root from itemdata.tsv
