universe = vanilla
executable = /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/regions/submissions/20260816T231425Z_U9region_core_W15_S8_np1_v1p0p1/scripts/run_region_parent.sh
arguments = --region-id $(region_id) --window-id $(window_id) --mode $(mode) --adaptive-id $(adaptive_id) --seed-id $(seed_id) --campaign-dir /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/regions/submissions/20260816T231425Z_U9region_core_W15_S8_np1_v1p0p1 --output-root $(node_output_root)
initialdir = /afs/cern.ch/user/c/cglenn/FCCWork/whizard/whizard_ttbar_spinpol/phase11_diagnostics/excess_weight_rootcause_v1/ttbar_restricted_region_suite_v1/regions/submissions/20260816T231425Z_U9region_core_W15_S8_np1_v1p0p1
should_transfer_files = NO
getenv = True
request_cpus = 1
request_memory = 3000MB
request_disk = 6000MB
+JobFlavour = "tomorrow"
output=logs/$(mode).$(ClusterId).$(ProcId).out
error=logs/$(mode).$(ClusterId).$(ProcId).err
log=logs/region_parent.$(ClusterId).log
notification=Never
queue
