find_package(HepMC3 CONFIG QUIET NO_MODULE)
if(TARGET HepMC3::HepMC3)
  set(HepMC3_FOUND TRUE)
  return()
endif()

set(_hepmc_hints)
foreach(var HEPMC3_ROOT HEPMC3_DIR HEPMC3)
  if(DEFINED ENV{${var}})
    list(APPEND _hepmc_hints "$ENV{${var}}")
  endif()
endforeach()
find_program(HEPMC3_CONFIG_EXECUTABLE HepMC3-config)
if(HEPMC3_CONFIG_EXECUTABLE)
  execute_process(COMMAND "${HEPMC3_CONFIG_EXECUTABLE}" --prefix
    OUTPUT_VARIABLE _hepmc_prefix OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  list(APPEND _hepmc_hints "${_hepmc_prefix}")
endif()
find_path(HEPMC3_INCLUDE_DIR HepMC3/GenEvent.h HINTS ${_hepmc_hints} PATH_SUFFIXES include)
find_library(HEPMC3_LIBRARY NAMES HepMC3 HINTS ${_hepmc_hints} PATH_SUFFIXES lib lib64)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HepMC3 REQUIRED_VARS HEPMC3_INCLUDE_DIR HEPMC3_LIBRARY)
if(HepMC3_FOUND AND NOT TARGET HepMC3::HepMC3)
  add_library(HepMC3::HepMC3 UNKNOWN IMPORTED)
  set_target_properties(HepMC3::HepMC3 PROPERTIES
    IMPORTED_LOCATION "${HEPMC3_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${HEPMC3_INCLUDE_DIR}")
endif()
mark_as_advanced(HEPMC3_INCLUDE_DIR HEPMC3_LIBRARY HEPMC3_CONFIG_EXECUTABLE)
